version: '3'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-15.3-alpine}
    container_name: ${PROJECT_NAME:-medusa-clothing-app}-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-medusa-clothing-app}
      POSTGRES_USER: ${POSTGRES_USER:-medusa-clothing-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-psqlData#12}
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_INITDB_ARGS: '-E UTF8 --locale=C'
    command: [ 'postgres', '-cshared_preload_libraries=pg_stat_statements' ]
    ports:
      - 5432:5432
    volumes:
      - medusa-clothing-database:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    name: ${PROJECT_NAME:-medusa-clothing-app}

volumes:
  medusa-clothing-database:
    name: ${POSTGRES_VOLUME_NAME:-medusa-clothing-database}
