version: '3'

services:

  medusa:
    build:
      context: ./medusa-clothing
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME:-medusa-clothing-app}-medusa
    depends_on:
      - postgres
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./medusa-clothing/.env.docker:/application/.env
    command: sh -c "npx medusa db:setup --db medusa-clothing-app && yarn dev"
    networks:
      - internal

networks:
  internal:
    external: true
